### ISSUE TITLE
hpool-miner-chia-pp v1.5.2-1 cannot be started

### ISSUE THREAD

**Issue by chaiguan** [h9-dev/chiapp-miner#16]
Please help to fix this. I encountered the below error when starting the latest version of miner-pp.

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)" x86_64

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f1b1d8b05ca]

runtime stack:
runtime.throw(0xa853a8, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 39 [syscall]:
runtime.cgocall(0x79e770, 0xc0001e25c0, 0xc00012c178)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0001e2590 sp=0xc0001e2558 pc=0x4097bb
net._C2func_getaddrinfo(0xc0001294d0, 0x0, 0xc00019cde0, 0xc00012c178, 0x0, 0x0, 0x0)
        /tmp/go-build2534136257/b090/_cgo_gotypes.go:91 +0x50 fp=0xc0001e25c0 sp=0xc0001e2590 pc=0x5a5750
net.cgoLookupIPCNAME.func1(0xc0001294d0, 0xe, 0xe, 0xc00019cde0, 0xc00012c178, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:161 +0xc5 fp=0xc0001e2608 sp=0xc0001e25c0 pc=0x5a9f85
net.cgoLookupIPCNAME(0xa73268, 0x3, 0xc0000ce018, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:161 +0x16b fp=0xc0001e2718 sp=0xc0001e2608 pc=0x5a674b
net.cgoIPLookup(0xc00012f0e0, 0xa73268, 0x3, 0xc0000ce018, 0xd)
        /usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0001e27b8 sp=0xc0001e2718 pc=0x5a6e87
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001e27c0 sp=0xc0001e27b8 pc=0x4773c1
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [select]:
net/http.(*Transport).getConn(0xd3aca0, 0xc000142c00, 0x0, 0xc000178800, 0x4, 0xc000154b60, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1368 +0x589
net/http.(*Transport).roundTrip(0xd3aca0, 0xc00019a500, 0xa66900, 0x101, 0xc00019a500)
        /usr/local/go/src/net/http/transport.go:579 +0x7eb
net/http.(*Transport).RoundTrip(0xd3aca0, 0xc00019a500, 0xd3aca0, 0xc0468c1e33a30c50, 0x6fc58ac96)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc00019a400, 0xaf1220, 0xd3aca0, 0xc0468c1e33a30c50, 0x6fc58ac96, 0xd78ce0, 0xc00012c160, 0xc0468c1e33a30c50, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc00019cc30, 0xc00019a400, 0xc0468c1e33a30c50, 0x6fc58ac96, 0xd78ce0, 0xc00012c160, 0x0, 0x1, 0x160)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc00019cc30, 0xc00019a400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0xc00015f7f8, 0xa73431, 0x4, 0xc000178800, 0x34, 0xc0001788c0, 0x3e, 0x40, 0xc00015f2e8, 0x4c5046, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x3c5
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0xc00015f7f8, 0xc000178800, 0x34, 0x7, 0xc000190e18, 0xa86059, 0x2d, 0xc000178840)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xc5
hpool.com/dev/miner-client/miner/server/line.(*Manager).update(0xc000156800)
        miner/server/line/manager.go:162 +0x59c
hpool.com/dev/miner-client/miner/server/line.NewManager(0xa82853, 0x24, 0xc00019c9f0)
        miner/server/line/manager.go:43 +0x1bc
hpool.com/dev/miner-client/miner/server.NewServer(0xa82853, 0x24, 0x0)
        miner/server/server.go:18 +0x53
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0xc0001ac240, 0xc00012c008, 0xa88088)
        miner/wrapper_miner.go:93 +0x305
hpool.com/dev/miner-client/platform.Run(0xc00015ff50, 0xc000100240, 0xafb7d8, 0xc0001ac240)
        platform/console.go:55 +0x76b
main.main()
        main.go:118 +0x5a8

goroutine 35 [select]:
net/http.(*Transport).getConn(0xd3aca0, 0xc0000a8040, 0x0, 0xa86688, 0x5, 0xc0000ce018, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1368 +0x589
net/http.(*Transport).roundTrip(0xd3aca0, 0xc0000c4100, 0xa66900, 0x7f1b20617f01, 0xc0000c4100)
        /usr/local/go/src/net/http/transport.go:579 +0x7eb
net/http.(*Transport).RoundTrip(0xd3aca0, 0xc0000c4100, 0xd3aca0, 0xc0468c1e33a49ab4, 0x6fc5a3b4d)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0000c4000, 0xaf1220, 0xd3aca0, 0xc0468c1e33a49ab4, 0x6fc5a3b4d, 0xd78ce0, 0xc0000c8008, 0xc0468c1e33a49ab4, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0000b60f0, 0xc0000c4000, 0xc0468c1e33a49ab4, 0x6fc5a3b4d, 0xd78ce0, 0xc0000c8008, 0x0, 0x1, 0x160)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0000b60f0, 0xc0000c4000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0xc000133bf8, 0xa73431, 0x4, 0xa86688, 0x2e, 0xc0000c0020, 0x1b, 0x20, 0x130d5f919d8944cc, 0x10, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x3c5
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0xc000133bf8, 0xa86688, 0x2e, 0x4, 0xc0000b8098, 0x0, 0x0, 0x0)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xc5
hpool.com/dev/miner-client/miner.(*Wrapper).CheckVersion(0xc0001ac240, 0xc0001e0528, 0x0, 0x0, 0x0, 0x0)
        miner/api.go:56 +0x195
hpool.com/dev/miner-client/miner.(*Wrapper).checkVersion(0xc0001ac240)
        miner/wrapper_miner.go:51 +0xb0
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1()
        miner/wrapper_miner.go:75 +0x2a
github.com/trying2016/common-tools/utils.SafeGo.func1(0x0, 0xc000111b50)
        vendor/github.com/trying2016/common-tools/utils/utils.go:183 +0x4f
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:166 +0x49

goroutine 36 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc00019c9f0)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 37 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc000111b70, 0xc00012c110)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 38 [select]:
net.(*Resolver).lookupIPAddr(0xd78320, 0xaf73e8, 0xc00012ef60, 0xa73268, 0x3, 0xc000154b60, 0x18, 0x50, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup.go:299 +0x65b
net.(*Resolver).internetAddrList(0xd78320, 0xaf73e8, 0xc00012ef60, 0xa73268, 0x3, 0xc000154b60, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0xd78320, 0xaf73e8, 0xc00012ef60, 0xa734fd, 0x4, 0xa73268, 0x3, 0xc000154b60, 0x1b, 0x0, ...)
        /usr/local/go/src/net/dial.go:221 +0x47d
net.(*Dialer).DialContext(0xc00012e300, 0xaf73e8, 0xc00012ef60, 0xa73268, 0x3, 0xc000154b60, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:403 +0x22b
net/http.(*Transport).dial(0xd3aca0, 0xaf73e8, 0xc00012ef60, 0xa73268, 0x3, 0xc000154b60, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1162 +0x1ff
net/http.(*Transport).dialConn(0xd3aca0, 0xaf73e8, 0xc00012ef60, 0x0, 0xc000178800, 0x4, 0xc000154b60, 0x1b, 0x0, 0xc000216000, ...)
        /usr/local/go/src/net/http/transport.go:1600 +0x1b85
net/http.(*Transport).dialConnFor(0xd3aca0, 0xc00016c420)
        /usr/local/go/src/net/http/transport.go:1442 +0xc6
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1411 +0x40f

goroutine 50 [select]:
net.cgoLookupIP(0xaf7378, 0xc00021a000, 0xa73268, 0x3, 0xc000154b60, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:229 +0x173
net.(*Resolver).lookupIP(0xd78320, 0xaf7378, 0xc00021a000, 0xa73268, 0x3, 0xc000154b60, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup_unix.go:96 +0x187
net.glob..func1(0xaf7378, 0xc00021a000, 0xc000214010, 0xa73268, 0x3, 0xc000154b60, 0x18, 0xc00012ef60, 0x0, 0xc000178800, ...)
        /usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:293 +0xba
internal/singleflight.(*Group).doCall(0xd78330, 0xc000204050, 0xc00021c000, 0x1c, 0xc00021a040)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2cc

goroutine 20 [select]:
net.(*Resolver).lookupIPAddr(0xd78320, 0xaf73e8, 0xc0000aa060, 0xa73268, 0x3, 0xc0000ce018, 0xd, 0x1bb, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup.go:299 +0x65b
net.(*Resolver).internetAddrList(0xd78320, 0xaf73e8, 0xc0000aa060, 0xa73268, 0x3, 0xc0000ce018, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0xd78320, 0xaf73e8, 0xc0000aa060, 0xa734fd, 0x4, 0xa73268, 0x3, 0xc0000ce018, 0x11, 0x0, ...)
        /usr/local/go/src/net/dial.go:221 +0x47d
net.(*Dialer).DialContext(0xc00012e300, 0xaf73e8, 0xc0000aa060, 0xa73268, 0x3, 0xc0000ce018, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:403 +0x22b
net/http.(*Transport).dial(0xd3aca0, 0xaf73e8, 0xc0000aa060, 0xa73268, 0x3, 0xc0000ce018, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1162 +0x1ff
net/http.(*Transport).dialConn(0xd3aca0, 0xaf73e8, 0xc0000aa060, 0x0, 0xa86688, 0x5, 0xc0000ce018, 0x11, 0x0, 0xc0000b8240, ...)
        /usr/local/go/src/net/http/transport.go:1600 +0x1b85
net/http.(*Transport).dialConnFor(0xd3aca0, 0xc0000e0000)
        /usr/local/go/src/net/http/transport.go:1442 +0xc6
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1411 +0x40f

goroutine 21 [select]:
net.cgoLookupIP(0xaf7378, 0xc0000a8080, 0xa73268, 0x3, 0xc0000ce018, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:229 +0x173
net.(*Resolver).lookupIP(0xd78320, 0xaf7378, 0xc0000a8080, 0xa73268, 0x3, 0xc0000ce018, 0xd, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup_unix.go:96 +0x187
net.glob..func1(0xaf7378, 0xc0000a8080, 0xc0000ba0d0, 0xa73268, 0x3, 0xc0000ce018, 0xd, 0xc0000aa060, 0x0, 0xa86688, ...)
        /usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:293 +0xba
internal/singleflight.(*Group).doCall(0xd78330, 0xc0000ac0a0, 0xc0000ce030, 0x11, 0xc0000a80c0)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2cc

goroutine 51 [syscall]:
net._C2func_getaddrinfo(0xc00021c040, 0x0, 0xc000210390, 0xc000206020, 0x0, 0x0, 0x0)
        /tmp/go-build2534136257/b090/_cgo_gotypes.go:91 +0x50
net.cgoLookupIPCNAME.func1(0xc00021c040, 0x19, 0x19, 0xc000210390, 0xc000206020, 0x0, 0xc0001e1ea0, 0x5a7532)
        /usr/local/go/src/net/cgo_unix.go:161 +0xc5
net.cgoLookupIPCNAME(0xa73268, 0x3, 0xc000154b60, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:161 +0x16b
net.cgoIPLookup(0xc000200420, 0xa73268, 0x3, 0xc000154b60, 0x18)
        /usr/local/go/src/net/cgo_unix.go:218 +0x67
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:228 +0xc7

**Comment by joesdu** [comment]
加一

**Comment by chaiguan** [comment]
Updated to latest version and it working fine now.

Miner:HPool-Miner-Chia-pp
Version:v1.5.2 2
BuildTime:2021-09-09-14:59:29 GMT

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chiapp-miner/releases 1.5.1-2已经修复
