### ISSUE TITLE
Where the Login Link to Bind?

### ISSUE THREAD

**Issue by tungpham-git** [h9-dev/chiapp-miner#2]
Where can i get the Login Link to Bind on Hpool chia miner-pp?

**Comment by trying2016** [comment]
https://www.hpool.co/help/tutorial/XCH%20PP-pool%20Mining
You can refer to the above tutorial settings

**Comment by tungpham-git** [comment]
> 
> 
> https://www.hpool.co/help/tutorial/XCH%20PP-pool%20Mining
> You can refer to the above tutorial settings

I was not scroll to below until you show me. So many thank to you.
