### ISSUE TITLE
PP最新的1.6.0的版本发成了OG的

### ISSUE THREAD

**Issue by thoreausolo** [h9-dev/chiapp-miner#21]
[HPool-Miner-chia-pp-v1.6.0-1-windows.zip]里点开hpool-miner-chia-console.exe，提示的是OG的锄头，实际运行起来也识别不了新协议的plot

ContextQueue init: 410
***************************************************
**** Miner:HPool-Miner-Chia-og
**** Version:v1.6.0 1
**** BuildTime:2023-03-21-08:24:10 GMT

**Comment by trying2016** [comment]
多谢反馈，已经修复
https://github.com/hpool-dev/chiapp-miner/releases/tag/1.6.0
