### ISSUE TITLE
可以让 xporxy 同时支持 og 池和 pp 池吗

### ISSUE THREAD

**Issue by Kayuii** [h9-dev/chiapp-miner#5]

**Comment by Kayuii** [comment]
xporxy 初始化时可以把 sqlite 数据库放到子目录里面吗？方便Docker重复挂载数据库，或者部分参数可以换成配置文件传进去，例如 管理员账号密码，apikey，线路这些

**Comment by trying2016** [comment]
开2个proxy，把端口设置成不同就可以了
